spring:
  # 테스트용 H2 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  # Redis 대신 임베디드 Redis 사용 설정
  data:
    redis:
      host: localhost
      port: 6370

  # 테스트 시 Docker Compose는 사용하지 않음
  docker:
    compose:
      enabled: false

# JWT 테스트 설정
jwt:
  secret-key: test_secret_key_should_be_long_enough_for_testing_purposes_minimum_512bit
  access-token-expiration: 3600000  # 1시간 (밀리초)
  refresh-token-expiration: 86400000  # 24시간 (밀리초)

# 서버 설정
server:
  port: 8080
# 로깅 설정
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG  # Security 관련 로그 활성화
    org.hibernate: INFO
    com.tistory.kmmoon.frankit: DEBUG