spring.application.name: frankit-assignment

springdoc:
  swagger-ui:
    enabled: true
    path: /api-docs
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
  api-docs:
    path: /api-docs/json
    groups.enabled: true
    enabled: true
  cache.disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  packages-to-scan: com.tistory.kmmoon.controller
  show-login-endpoint: true
